--- #PROMPT FOR USER PACKAGE EXAMPLE
- hosts: all
  user: raman
  become: true
  become_method: sudo
  connection: ssh
  gather_facts: no
  vars: 
    playbook_version: 0.01b
  vars_prompt:
    - name: pkgtoinstall
      prompt: Install which package?
      default: telnet
      private: no
  tasks:
    - name: Install the dedicated package
      apt: pkg={{ pkgtoinstall }} state=present
