---
- hosts: all
  become: true
  become_method: sudo
  user: raman
  connection: ssh
  gather_facts: no
  tasks:
    - name: Install Telnet and Lynx
      apt: pkg={{ item }} state=latest
      with_items:
      - lynx
      - telnet
      tags:
      - packages
    - name: Verify telnet got installed
      raw: dpkg --get-selections | grep telnet > /home/raman/package.log
      tags:
      - verification 
