---
- hosts: all
  become: true
  become_method: sudo
  user: raman
  connection: ssh
  gather_facts: yes
  tasks:
    - name: Installing apache
      apt: pkg=apache2 state=latest
    - name: Verify service status
      shell: service apache2 status
      register: result
      until: result.stdout.find("running") != -1
      retries: 5
      delay: 5
    - debug: var=result 
