---
- hosts: db 
  user: root
  gather_facts: yes
  tasks: 
   - name: Date/time stamp for playbook starts
     command: /bin/date
     register: timestamp_start
   - debug: var=timestamp_start
   - name: Install apache
     apt: pkg=apache2 state=present
     notify: Start HTTPD
   - name: install client software
     apt: name=telnet state=latest
   - name: install client software lynx
     apt: pkg=lynx state=latest
   - name: log all pkgs install on system
     command: apt list --installed
     register: log_result
   - debug: var=log_result
   - name: date/time stamp for when playbook ends
     command: /bin/date
     register: timestamp_end
   - debug: var=timestamp_end
  handlers:
   - name: Start HTTPD
     service: name=apache2 state=restarted 
